services:
  flutter_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"   # Hosting Emulator
      - "8080:8080"   # Firestore Emulator
      - "9099:9099"   # Authentication Emulator
      - "4001:4001"   # Emulator UI
      - "9150:9150"   # Firestore Emulator Websocket
    volumes:
      - .:/app
    environment:
      - FLUTTER_ENV=production
    command: >
      sh -c "FLUTTER_SUPPRESS_ROOT_WARNING=true firebase emulators:start --only auth,firestore,hosting"
    restart: unless-stopped
