name: sanamente
description: "Proyecto Flutter para monitoreo del estado de ánimo."

# Previene que se publique accidentalmente a pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase core para inicializar Firebase
  firebase_core: ^2.10.0
  # Firebase Auth para autenticación
  firebase_auth: ^4.8.0
  # Firestore para almacenamiento de datos
  cloud_firestore: ^4.8.0


  # Paquete para manejar archivos .env
  flutter_dotenv: ^5.2.1
  # Otros paquetes útiles
  cupertino_icons: ^1.0.8

  #device preview
  device_preview: ^1.0.0

#http
  http: ^0.13.4

  ## logger
  logger: ^1.1.0

  #provider
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Buenas prácticas de linting
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Sección para agregar archivos y assets estáticos
  assets:
    - .env
    - assets/identificacion_mock.json
