name: sanamente
description: "Proyecto Flutter para monitoreo del estado de ánimo."

# Previene que se publique accidentalmente a pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase core para inicializar Firebase
  firebase_core: ^3.9.0
  # Firebase Auth para autenticación
  firebase_auth: ^5.3.4
  # Firestore para almacenamiento de datos
  cloud_firestore: ^5.6.0


  # Paquete para manejar archivos .env
  flutter_dotenv: ^5.2.1
  # Otros paquetes útiles
  cupertino_icons: ^1.0.8

  #device preview
  device_preview: ^1.0.0

#http
  http: ^1.2.2

  ## logger
  logger: ^2.5.0

  #provider
  provider: ^6.0.5

  ## fl chart
  fl_chart: ^0.70.0

  ## FLUTTER LOCAL NOTIFICAIONES
  flutter_local_notifications: ^18.0.1

  ##TIMEZONE

  timezone: ^0.10.0

  ##table calendar
  table_calendar: ^3.0.9

  syncfusion_flutter_charts: ^28.1.35

  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  # Buenas prácticas de linting
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Sección para agregar archivos y assets estáticos
  assets:
    - .env
    - assets/identificacion_mock.json
