// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAENjMJa406Er42RuQ22E4l1mmJYg3tMc4',
    appId: '1:501072482046:web:099dd3fa6fc6a5de205faf',
    messagingSenderId: '501072482046',
    projectId: 'app-sanamente',
    authDomain: 'app-sanamente.firebaseapp.com',
    storageBucket: 'app-sanamente.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_WP9uwm_OdqTG-CxdZ3Zrzmmc-6TsSxQ',
    appId: '1:501072482046:android:6929f1eab4ef6b5f205faf',
    messagingSenderId: '501072482046',
    projectId: 'app-sanamente',
    storageBucket: 'app-sanamente.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu0Ee5EfqYVnLN7sXnhXQpzYkcd__OhNc',
    appId: '1:501072482046:ios:f8b75960e6a1af2d205faf',
    messagingSenderId: '501072482046',
    projectId: 'app-sanamente',
    storageBucket: 'app-sanamente.firebasestorage.app',
    iosBundleId: 'com.example.sanamente',
  );

}